<?php

namespace ContainerQ1aU8Yx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProcessFileCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ProcessFileCommand' shared autowired service.
     *
     * @return \App\Command\ProcessFileCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ProcessFileCommand.php';

        $container->privates['App\\Command\\ProcessFileCommand'] = $instance = new \App\Command\ProcessFileCommand(\dirname(__DIR__, 4), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setName('app-process-file');

        return $instance;
    }
}
