<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container606A2DE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container606A2DE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container606A2DE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container606A2DE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container606A2DE\App_KernelDevDebugContainer([
    'container.build_hash' => '606A2DE',
    'container.build_id' => '98f87b48',
    'container.build_time' => 1647767858,
], __DIR__.\DIRECTORY_SEPARATOR.'Container606A2DE');
